new chat service
NikitaSarin/Stroganina pull request #21
Opened 2022-03-22 11:49 UTC by shsanek

алгоритмы работают (вроде) но код надо подразгребсти

2022-03-22 16:32 UTC, NikitaSarin requested changes

2022-03-22 16:32 UTC, NikitaSarin commented on NetworkApi/Sources/NetworkApi/Models/Message.swift
> +        public let user: User?
почему так?

2022-03-22 16:32 UTC, NikitaSarin commented on Stroganina/Flows/Main/Chat/ChatService/ChatService+Message.swift
> +        var provider: MessageProvider {
очень сложная структура выходит 
Container -> Provider -> Wrapper -> Type -> Base
нужно погрумить целевое, такое усложнение не пойдет

2022-03-22 16:32 UTC, NikitaSarin commented on Stroganina/Flows/Main/Chat/ChatViewModel.swift
> +    @Published var history = [ChatItem]()
- [ ] чот не так, были сообщения стали чаты

2022-03-22 16:32 UTC, NikitaSarin commented on Stroganina/Views/Messages/TextMessageRow.swift
> +        if #available(iOS 15, *) {
- [ ] поднять версию

2022-03-22 16:32 UTC, NikitaSarin commented on Stroganina/Models/Mapping/Message+Raw.swift
> +            user: raw.user.flatMap { User($0) },
User(raw.user)

2022-03-22 16:32 UTC, NikitaSarin commented on Stroganina/Flows/Main/Chat/ChatView.swift
> +                                viewModel.useItem(item)
- [ ] viewDidShow(item)

2022-03-22 16:35 UTC, shsanek commented on Stroganina/Flows/Main/Chat/ChatView.swift
> +struct ChatItemView: View {
ооо без нее swiftUI заваливаеться

2022-03-22 16:35 UTC, shsanek commented on Stroganina/Flows/Main/ChatList/ChatRow.swift
> +                    if #available(iOS 15, *) {
да необезательно

2022-03-26 19:22 UTC, shsanek commented on NetworkApi/Sources/NetworkApi/Models/Message.swift
> +        public let user: User?
поправлено

2022-04-01 13:50 UTC, merged